docs/usage.md, packages/babel-helper-define-polyfill-provider/src/index.js, packages/babel-helper-define-polyfill-provider/src/types.js, packages/babel-helper-define-polyfill-provider/test/options.js
This new API has the same goal as the include/exclude options
(for this reason, it will throw an error if you try to use both), but
both have some advantages that the other one doesn't have:
1) include/exclude are an array, so you can use them
in a static JSON file. Also, they might be easier to use.
2) shouldInjectPolyfill is a function, so it is more powerful: for
example, you could use it to store somewhere a list of all
the injected polyfill, or to throw an error if a specific
polyfill would be injected (maybe because it's too big and
you want to be sure that you don't rely on it)
Fixes https://github.com/babel/babel-polyfills/issues/10, fixes https://github.com/babel/babel/issues/11583 (cc @niftylettuce), fixes https://github.com/babel/babel/issues/6625,  can fix …
=> Add a `shouldInjectPolyfill` option to polyfill providers

packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.js
The other way to fix this would be to include it in shipped proposals. Effectively this is getting filtered out unless `proposals: true` is set when it shouldn't be since it's shipped and stage 4
=> fix: Promise.allSettled not included when it should be

packages/babel-helper-define-polyfill-provider/src/index.js, packages/babel-helper-define-polyfill-provider/test/options.js
Fixes #35 
preset-env code: https://github.com/babel/babel/blob/44f8287d7ac3c523a9425a7bb4beb4882090ae20/packages/babel-preset-env/src/normalize-options.js#L121-L127 (I'm not sure about what that comment means)
=> Allow targets to be a string/array

packages/babel-plugin-polyfill-regenerator/src/index.js, packages/babel-plugin-polyfill-regenerator/test/fixtures/usage-global/all/output.mjs, packages/babel-plugin-polyfill-regenerator/test/fixtures/usage-global/async/output.mjs, packages/babel-plugin-polyfill-regenerator/test/fixtures/usage-global/generator/output.mjs
https://github.com/babel/babel/commit/1382437ad61aeeae9fba87c880517a7167df5a14. These packages already added the extension for core-js, but not for regenerator.
=> Add .js extension to regenerator import

packages/babel-helper-define-polyfill-provider/src/dependencies.js
This is the same as https://github.com/babel/babel/pull/12439.
TL;DR we can use the native `require.resolve` in Node.js >= 8, and it's important to do so because Next.js breaks the `resolve` package.
I think a custom plugin was overkill here, so I just modified the code to use the native `require.resolve` when it supports the `paths` option.
Ref: https://github.com/babel/babel/pull/12583#discussion_r551054800
=> Use native require.resolve when available

packages/babel-helper-define-polyfill-provider/package.json, packages/babel-helper-define-polyfill-provider/src/imports-cache.js, packages/babel-helper-define-polyfill-provider/test/injectors.js, yarn.lock
Fixes https://github.com/babel/babel/pull/12583#discussion_r554009945
=> Avoid duplicate side-effects-only `require()` calls

packages/babel-helper-define-polyfill-provider/src/index.js, packages/babel-plugin-polyfill-corejs3/test/fixtures/top-level-targets/simple/input.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/top-level-targets/simple/options.json, packages/babel-plugin-polyfill-corejs3/test/fixtures/top-level-targets/simple/output.mjs
This feature is for the helper package (not only for corejs3), but I added a test in corejs3 to show the behavior.
=> Use the top-level `targets` option

packages/babel-plugin-polyfill-corejs2/src/index.js, packages/babel-plugin-polyfill-corejs2/test/fixtures/usage-global/unknown-polyfill/input.mjs, packages/babel-plugin-polyfill-corejs2/test/fixtures/usage-global/unknown-polyfill/options.json, packages/babel-plugin-polyfill-corejs2/test/fixtures/usage-global/unknown-polyfill/output.mjs
Fix `Internal error in the corejs2 provider: unknown polyfill "web.dom.iterable"`
Related discussion https://github.com/babel/babel/pull/12870#issuecomment-784574841
=> fix: avoid injecting uknown polyfill

docs/usage.md
It's awesome that this works (once I used the correct name.)
=> Fix typo in documentation (absoluteRuntime -> absoluteImports)

packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.js, packages/babel-plugin-polyfill-corejs3/test/fixtures/top-level-targets/simple/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/all-proposals/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/all/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/built-in-from-global-object/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/determanated-instance-methods/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/dynamic-import-webpack/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/dynamic-import/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/evaluated-class-methods/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/fetch/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/in/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/instance-methods/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/modules-transform/output.js, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/object-destructuring/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/promise-all/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/promise-finally/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/promise-race/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/shippedProposals/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/source-type-script-query/output.js, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/source-type-script/output.js, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/symbol-iterator-in/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/symbol-iterator/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/timers/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/typed-array-edge-13/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/typed-array-static/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/typed-array/output.mjs
This PR ensures that we inject dependencies _before_ the polyfill that depends on them. You can use [this 7.12.0 repl](https://babeljs.io/repl/version/7.12.0) to test the old behavior.
Fixes https://github.com/babel/babel-polyfills/issues/77.
=> [corejs3] Inject `usage-global` imports in the correct order

packages/babel-helper-define-polyfill-provider/src/index.js
I found this while updating these packages in Babel.
In Node.js `getTargets` is the `.default` property of the `default` import, while in bundlers (or in compiled code) it's the `default` export itself.
=> Fix compatibility with native ESM interop

packages/babel-helper-define-polyfill-provider/src/index.js
I noticed this because of the log in https://github.com/babel/babel/runs/2671118012: it logs but the polyfill is correctly installed.
=> Add `dirname` to the cache key for missing dependencies

CONTRIBUTING.md, README.md, docs/polyfill-provider.md
adds a simple `CONTRIBUTING.md` based on / similar to [Babel core's `CONTRIBUTING.md`](https://github.com/babel/babel/blob/main/CONTRIBUTING.md)
- none existed, so I had to figure out how to set-up the repo myself
when trying to contribute code and tests
- references [Babel core's `CONTRIBUTING.md`](https://github.com/babel/babel/blob/main/CONTRIBUTING.md) and [`docs/polyfill-provider.md`](https://github.com/babel/babel-polyfills/blob/main/docs/polyfill-provider.md)
- also fix a tiny typo in `polyfill-provider.md`
- add a "Want to contribute?" section to `README` similar to
[Babel core's `README`](https://github.com/babel/babel#want-to-contribute-to-babel)
I was working on PRs for #17 and #36 (respectively, #118 and #119 ) and the first step for that was figuring out how to set-up the …
=> docs: add a simple CONTRIBUTING.md

docs/migration.md
Follow-up to 1091fa4e27a597148403545d21e776dadeb5c518
- 1091fa4e27a597148403545d21e776dadeb5c518 switched the examples to use
top-level targets, but this note at the top was leftover
- in the same commit, the comments within JSON were removed, so the
syntax highlighting can be set back to regular JSON instead of
JSON5 or JSONC
- Notably, GitHub was not correctly rendering anything other than JSON
- also fix syntax highlighting within an HTML table by using
HTML `<code>` blocks instead of Markdown backticks
Here's what the improperly highlighted sections looked like on GitHub (both the JSON5 and the backticks):
Can see the before/after below:
[Old Markdown Preview](https://github.com/babel/babel-polyfills/blob/1091fa4e27a597148403545d21e776dadeb5c518/docs/migration.md#es-shims) vs. [New …
=> docs: remove leftover references to duplicate targets

packages/babel-helper-define-polyfill-provider/src/index.js, packages/babel-helper-define-polyfill-provider/test/options.js
adds a detailed error message when no options are provided to a polyfill plugin as requested in #17
- previously, if polyfills were ran without options, it would just
throw ".method must be a string", which is not very intuitive
- now, say that the plugin requires options, give an example of a
config with options, and link to the docs for further reference
- add a test for this new error as well
I haven't used Flow before (only TS), so let me know if I should have done some flow typing anywhere.
(for context: I was thinking I could put a type-guard or something around `isEmpty`, but given that that's a more advanced TS feature, I was not really sure how to do so in Flow)
Fixes #17
=> feat: better error message when no options are provided

README.md, packages/babel-plugin-polyfill-es-shims/README.md
The plugins have been well tested thanks to preset-env, they are safe to use.
Also, I sorted the es-shims features list from newest to oldest, since people are more likely to be interested in polyfills for new features than for functions supported virtually everywhere. The readme still mentions that ES5 and ES6 are not fully supported yet.
=> Remove experimental warning, reorganize es-shims features list

packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.ts, packages/babel-plugin-polyfill-es-shims/README.md, packages/babel-plugin-polyfill-es-shims/data/polyfills.json, packages/babel-plugin-polyfill-es-shims/src/mappings.ts, packages/babel-plugin-polyfill-es-shims/test/fixtures/usage-global/proposal-change-array-by-copy/input.mjs, packages/babel-plugin-polyfill-es-shims/test/fixtures/usage-global/proposal-change-array-by-copy/options.json, packages/babel-plugin-polyfill-es-shims/test/fixtures/usage-global/proposal-change-array-by-copy/output.mjs, packages/babel-plugin-polyfill-es-shims/test/fixtures/usage-global/proposal-change-array-by-copy/stderr.txt, packages/babel-plugin-polyfill-es-shims/test/fixtures/usage-pure/proposal-change-array-by-copy/input.mjs, packages/babel-plugin-polyfill-es-shims/test/fixtures/usage-pure/proposal-change-array-by-copy/options.json, packages/babel-plugin-polyfill-es-shims/test/fixtures/usage-pure/proposal-change-array-by-copy/output.mjs, packages/babel-plugin-polyfill-es-shims/test/fixtures/usage-pure/proposal-change-array-by-copy/stderr.txt, scripts/build-es-shims-data/es-shims-features.js, scripts/build-es-shims-data/index.js
I also added `findLast`/`findLastIndex` to the readme, because they have been supported since #94.
I didn't add the group-by proposal yet, to wait for the new name.
=> [es-shims] Add change-array-by-copy proposal methods

packages/babel-plugin-polyfill-corejs3/src/index.ts, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/super-call/input.js, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/super-call/options.json, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/super-call/output.js
Avoid super call transformation which is unespected:
```ts
class List {
map() {
return;
}
}
class TreeNodeList extends List {
constructor() {
// In current version
// Compiled to `_mapInstanceProperty(super)`
super.map;
// Compiled to _mapInstanceProperty(_context = super).call(_context);
super.map();
}
}
```
Instead, babel polyfill plugin should skip the case.
=> fix: avoid transpile super call

.github/workflows/ci.yml
ref: https://github.com/babel/babel-polyfills/pull/149#issuecomment-1369003357
I don't know why it suddenly fails without any changes (I can't reproduce it locally.), but I should have found the reason.
jest's default maxWorkers==1 in CI (cpu ==2), which means that there is no complete isolation test.
https://github.com/babel/babel-polyfills/blob/798db9d4b3e3096fd6fc5b48c2fedd78e948b6b8/packages/babel-helper-define-polyfill-provider/src/node/dependencies.ts#L71
=> fix: CI fails on windows

packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.ts, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/all-corejs-3.21/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/all-proposals-corejs-3.20/output.mjs, yarn.lock
Fixes https://github.com/babel/babel-polyfills/issues/152.
Here they are:
- https://unpkg.com/browse/core-js-pure@3.27.2/stable/regexp/dot-all.js
- https://unpkg.com/browse/core-js-pure@3.27.2/stable/regexp/sticky.js
=> (corejs3): fixed dot-all/sticky definitions

packages/babel-helper-define-polyfill-provider/src/index.ts, packages/babel-helper-define-polyfill-provider/src/types.ts, packages/babel-helper-define-polyfill-provider/test/misc.js, packages/babel-plugin-polyfill-corejs2/src/index.ts, packages/babel-plugin-polyfill-corejs3/src/index.ts, packages/babel-plugin-polyfill-corejs3/src/utils.ts, packages/babel-plugin-polyfill-regenerator/src/index.ts
The goal of this new API is that any polyfill provider can specify their own polyfilled version of `@babel/runtime` (such as `@babel/runtime-corejs3`), instead of hard-coding `@babel/runtime`, `@babel/runtime-corejs2` and `@babel/runtime-corejs3` in `@babel/plugin-transform-runtime`.
This is done by returning a `runtimeName: string` property in the polyfill provider result object, which will be picked up by `@babel/plugin-transform-runtime` when injecting helpers.
See https://github.com/babel/babel/pull/15531 for the other part of this change. This PR needs to land first.
=> Implement new transform-runtime protocol for runtime package name

packages/babel-plugin-polyfill-corejs2/src/built-in-definitions.ts, packages/babel-plugin-polyfill-corejs2/test/fixtures/usage-pure/aliased-constructors/output.js, packages/babel-plugin-polyfill-corejs2/test/fixtures/usage-pure/built-in-globals/output.js, packages/babel-plugin-polyfill-corejs2/test/fixtures/usage-pure/built-in-static-methods/output.js, packages/babel-plugin-polyfill-corejs2/test/fixtures/usage-pure/es6-for-of/output.js
`symbol.js` in https://unpkg.com/browse/core-js@2.6.12/library/fn/ doesn't exist, so we have to use `symbol/index.js`. All the other pure polyfills for globals that we inject have the `<name>.js` file; this is the only exception.
=> [corejs2] Fix import of the symbol pure polyfill

packages/babel-helper-define-polyfill-provider/package.json, packages/babel-plugin-polyfill-corejs2/package.json, packages/babel-plugin-polyfill-corejs3/package.json, packages/babel-plugin-polyfill-es-shims/package.json, packages/babel-plugin-polyfill-regenerator/package.json, yarn.lock
The minimum `@babel/core` version can be safely bumped to 7.4.0 in all packages, since it's what `@babel/helper-define-polyfill-provider` already requires.
=> Allow Babel 8 pre-releases in peerDeps

packages/babel-plugin-polyfill-corejs3/package.json, packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.ts, packages/babel-plugin-polyfill-corejs3/src/index.ts, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/decorators/input.js, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/decorators/options.json, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-global/decorators/output.js, yarn.lock
Ref https://github.com/babel/babel/pull/15895
=> [corejs3] Inject `esnext.symbol.metadata` for decorated classes

packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.ts, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/all-corejs-3.21/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/all-corejs-3.24/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/all-corejs-3.27/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/all-corejs-3.28/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/all-corejs-3.30/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/all-corejs-3.31/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/all-corejs-3.32/output.mjs, packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/all-proposals-corejs-3.20/output.mjs
Existing definition leads to wrong import statement to be generated.
See #185
=> Fix reference to dom-exception.
